### ISSUE TITLE
Set up Travis build

### ISSUE THREAD

**Issue by chelseakomlo** [twtiger/toy-dns-nameserver#2]

**Comment by chelseakomlo** [comment]
If we are doing the resolver and server in different languages, should we have two separate repos/builds for these?

**Comment by olabini** [comment]
It depends on if you're going to run them separately. In general, things should be isolated from each other as much as possible and that applies here too.

**Comment by olabini** [comment]
I mean I assume the two different parts will be in different repos, right?

**Comment by chelseakomlo** [comment]
Yes, actually after thinking about it, having these separated makes sense. I saw that STRIKE had toytls all in one repo, but having this separated is better.

**Comment by olabini** [comment]
The client and the server shares a LOT of code for TLS - AND, they are in the same language.
